source 'https://rubygems.org'
gem 'sass', '~>3.2.9'
gem 'sass-globbing', '~>1.1.0'
gem 'compass', '~>0.12.2'
gem 'chunky_png', '>=1.2.8'
gem 'zurb-foundation', '4.3.1'
# gem 'compass-rgbapng', '>=0.1.1'